#!/usr/bin/env python

import argparse
import os.path
import subprocess

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPTS_DIR)
ANSIBLE_DIR = os.path.join(ROOT_DIR, "ansible")
SITE_DIR = os.path.join(ROOT_DIR, "site")
BUILD_DIR = os.path.join(SITE_DIR, "_site")


def build():
    print "Building site..."
    os.chdir(SITE_DIR)
    subprocess.check_call(["jekyll", "build"])


def serve():
    print "Serving site..."
    os.chdir(SITE_DIR)
    subprocess.check_call(["jekyll", "serve"])


def deploy():
    print "Deploying site..."
    os.chdir(ANSIBLE_DIR)
    subprocess.check_call(["ansible-playbook", "gameplaycolor.yml"])    


def command_build(parser):

    def inner(options):
        build()

    return inner


def command_serve(parser):

    def inner(options):
        serve()

    return inner


def command_deploy(parser):

    def inner(options):
        build()
        deploy()

    return inner


def add_command(subparsers, name, command, help=""):
  parser = subparsers.add_parser(name, help=help)
  fn = command(parser)
  parser.set_defaults(fn=fn)


def main():
    parser = argparse.ArgumentParser(description="Site management script.")
    subparsers = parser.add_subparsers(help="Command to run.")
    add_command(subparsers, name="build", command=command_build, help="Build the site.")
    add_command(subparsers, name="serve", command=command_serve, help="Serve the site.")
    add_command(subparsers, name="deploy", command=command_deploy, help="Deploy the site.")
    options = parser.parse_args()
    options.fn(options)


if __name__ == "__main__":
    main()
