# Site settings
title: Game Play Color
email: support@inseven.co.uk
baseurl: ""
url: "https://inseven.co.uk"

navigation:
  - text: "FAQ"
    url: "/faq/"
  - text: "Releases"
    url: "/changelog/"
  - text: "Code"
    url: "https://github.com/gameplaycolor/gameplaycolor"
    target: _blank
  - text: "Privacy Policy"
    url: "/privacy-policy/"

# Build settings
markdown: kramdown
