# Site settings
title: Game Play Color
baseurl: ""
url: "https://gameplaycolor.com"

navigation:
  - text: "FAQ"
    url: "/faq/"
  - text: "Release Notes"
    url: "/releases/"
  - text: "Privacy Policy"
    url: "/privacy-policy/"
  - text: "GitHub"
    url: "https://github.com/gameplaycolor/gameplaycolor"
    target: _blank

# Build settings
markdown: kramdown
